### ISSUE TITLE
Not compatible with Redmine 3.4

### ISSUE THREAD

**Issue by vphantom** [jbbarth/redmine_refresh#8]
Hello! Just FYI, this plugin prevents Redmine 3.4.2 from starting at all:

```text
  Message from application: uninitialized constant ActiveSupport::Reloader (NameError)
  /var/www/redmine/plugins/redmine_refresh/init.rb:3:in `<top (required)>'
  /var/www/redmine/lib/redmine/plugin.rb:155:in `block in load'
  /var/www/redmine/lib/redmine/plugin.rb:146:in `each'
  /var/www/redmine/lib/redmine/plugin.rb:146:in `load'
  /var/www/redmine/config/initializers/30-redmine.rb:21:in `<top (required)>'
  /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:652:in `block in load_config_initializer'
  /var/lib/gems/2.3.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:166:in `instrument'
  /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:651:in `load_config_initializer'
  /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
  /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:615:in `each'
  /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/engine.rb:615:in `block in <class:Engine>'
  /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `instance_exec'
  /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:30:in `run'
  /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:55:in `block in run_initializers'
  /usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
  /usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
  /usr/lib/ruby/2.3.0/tsort.rb:422:in `block (2 levels) in each_strongly_connected_component_from'
  /usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
  /usr/lib/ruby/2.3.0/tsort.rb:421:in `block in each_strongly_connected_component_from'
  /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `each'
  /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:44:in `tsort_each_child'
  /usr/lib/ruby/2.3.0/tsort.rb:415:in `call'
  /usr/lib/ruby/2.3.0/tsort.rb:415:in `each_strongly_connected_component_from'
  /usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
  /usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
  /usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
  /usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
  /usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
  /usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
  /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/initializable.rb:54:in `run_initializers'
  /var/lib/gems/2.3.0/gems/railties-4.2.8/lib/rails/application.rb:352:in `initialize!'
  /var/www/redmine/config/environment.rb:14:in `<top (required)>'
  config.ru:3:in `require'
  config.ru:3:in `block in <main>'
  /var/lib/gems/2.3.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `instance_eval'
  /var/lib/gems/2.3.0/gems/rack-1.6.8/lib/rack/builder.rb:55:in `initialize'
  config.ru:1:in `new'
  config.ru:1:in `<main>'
  /var/lib/gems/2.3.0/gems/passenger-5.1.7/src/helper-scripts/rack-preloader.rb:110:in `eval'
  /var/lib/gems/2.3.0/gems/passenger-5.1.7/src/helper-scripts/rack-preloader.rb:110:in `preload_app'
  /var/lib/gems/2.3.0/gems/passenger-5.1.7/src/helper-scripts/rack-preloader.rb:156:in `<module:App>'
  /var/lib/gems/2.3.0/gems/passenger-5.1.7/src/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
  /var/lib/gems/2.3.0/gems/passenger-5.1.7/src/helper-scripts/rack-preloader.rb:29:in `<main>'
```

**Comment by nanego** [comment]
Hello
The latest version of the plugin is only compatible with Redmine 4.
To use it with Redmine 3, you will have to use this release:
https://github.com/jbbarth/redmine_refresh/tree/v3.4.6

**Comment by vphantom** [comment]
Ah ha! Thank you!

**Comment by vphantom** [comment]
Argh, sorry but even branch `v3.4.6` crashes our server.  The error differs, though:

```text
  Message from application: Redmine::PluginNotFound (Redmine::PluginNotFound)
  /var/www/redmine/lib/redmine/plugin.rb:123:in `find'
  /var/www/redmine/lib/redmine/plugin.rb:251:in `requires_redmine_plugin'
  /var/www/redmine/plugins/redmine_refresh/init.rb:16:in `block in <top (required)>'
  /var/www/redmine/lib/redmine/plugin.rb:75:in `instance_eval'
  /var/www/redmine/lib/redmine/plugin.rb:75:in `register'
  /var/www/redmine/plugins/redmine_refresh/init.rb:7:in `<top (required)>'
[...]
```

**Comment by nanego** [comment]
You will have to install the redmine_base_deface plugin

**Comment by vphantom** [comment]
Argh, sorry for having missed that. :man_facepalming:
